# Generated by Django 4.2.6 on 2023-10-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrelations',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
