# Generated by Django 4.2.7 on 2023-11-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'offline'), ('offline', 'online')], default='offline', max_length=10),
        ),
    ]
