# Generated by Django 4.2.7 on 2023-11-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.ManyToManyField(limit_choices_to=5, related_name='tags', to='gallery.imagetag'),
        ),
    ]
