# Generated by Django 4.2.7 on 2023-11-06 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_bookinpdf_options_alter_bookinpdf_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinpdf',
            name='pdf',
            field=models.FileField(upload_to='book_in_pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
