# Generated by Django 4.2.6 on 2023-11-02 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_requests', '0003_historyrequests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyrequests',
            options={'verbose_name_plural': 'History Requests'},
        ),
        migrations.AddField(
            model_name='historyrequests',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historyrequests',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
