# Generated by Django 4.2.6 on 2023-10-24 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_relations', '0002_alter_bookrelations_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrelations',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_relation', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookrelations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rait', to=settings.AUTH_USER_MODEL),
        ),
    ]
