# Generated by Django 4.2.7 on 2023-11-03 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookinpdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinpdf',
            options={'verbose_name_plural': 'Books_in_pdf'},
        ),
        migrations.AlterField(
            model_name='bookinpdf',
            name='pdf',
            field=models.FileField(upload_to='book_in_pdf/', validators=[django.core.validators.FileExtensionValidator('pdf')]),
        ),
    ]
