# Generated by Django 4.2.6 on 2023-11-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('open', 'open'), ('fail', 'failed'), ('comp', 'complete')], max_length=4),
        ),
    ]
